### ISSUE TITLE
Unable to run Many gguf quantized models that are officially and unofficial supported by xinference

### ISSUE THREAD

**Issue by Greatz08** [xorbitsai/inference#2796]
### System Info / 系統信息

Arch linux

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Used docker pull xprobe/xinference:latest so i believe you can consider it as latest version of xinference if images are been updated.

### The command used to start Xinference / 用以启动 xinference 的命令

used docker compose which i created for myself : 

```
services:
  xinference:
    image: xprobe/xinference:latest
    command: xinference-local -H 0.0.0.0
    ports:
      - "9997:9997"
    volumes:
      - ./data/.xinference:/root/.xinference
      - ./data/.cache/huggingface:/root/.cache/huggingface
      - ./data/.cache/modelscope:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

### Reproduction / 复现过程

I Used docker pull xprobe/xinference:latest to pull latest xinference and it is working perfectly fine BUT their are some issues which i would like to discuss below : 
1. I tried to download today deepseek-r1 14b and 1b variants Q4 quantized from main page of xinference and got similar error which i showed below with attached image.
2. Then i downloaded different gguf model with different quantization from huggingface which was FuseO1-DeepSeekR1-Qwen2.5-Coder-32B-Preview-v0.1-IQ2_XS.gguf and you can see it didnt worked (similar error i for for above point) 

![Image](https://github.com/user-attachments/assets/0dd1f362-24aa-4140-87b2-9553f75fb8ca)

3.Then i tried to download old llama model from hugginface which was Llama-3.2-3B-Instruct-Q4_K_S.gguf and added it with custom model and used it and it was working fine.
4. I tried some transformer based models and they did work fine too.

So i dont know exactly what can be the cause of this issue and how it can be resolved. What i did and what worked and what didnt worked i tried to explained , still if you have any doubts regarding this issue then do let me know i will try to give more information.
Hope to fix this because i love this project and i want to use it instead of ollama. Latest version of ollama is able to run all these models which xinference is unable to run. My guess for this problem is that something is wrong with xinference llama.cpp , hope you can figure it out so that we can run new gguf quantized models easily.

Thankyou very much for this great project

### Expected behavior / 期待表现

Should be running all latest gguf different quantized models like ollama is able to.
