### ISSUE TITLE
OpenAI方式调用返回参数choices为空，

### ISSUE THREAD

**Issue by superstring** [xorbitsai/inference#2947]
### System Info / 系統信息

cuda: 12.4
os: ubuntu 22.3
gpu-driver: 550.144.03

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v1.3.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker-compose up -d 

```yaml
version: '3'
services:
  xinference:
    image: xprobe/xinference:v1.3.0
    ports:
      - "9997:9997"
    volumes:
      - /mnt/sdb/.xinference:/root/.xinference
      - /mnt/sdb/.cache/huggingface:/root/.cache/huggingface
      - /mnt/sdb/.cache/modelscope:/root/.cache/modelscope
      - /mnt/sdb/.config/xinference_config.json:/root/.config/xinference_config.json
    environment:
      - XINFERENCE_MODEL_SRC=modelscope 
    shm_size: '128g'
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2', '3']
              capabilities: [gpu]
    command: xinference-local -H 0.0.0.0 --auth-config /root/.config/xinference_config.json
```

### Reproduction / 复现过程

1. 使用vllm部署 deepseek-r1-distill-qwen-32b-gptq-int4
2. 使用openai方式调用
```py
import openai

client = openai.Client(
    api_key=os.getenv("XINFERENCE_API_KEY"),
    base_url=os.getenv("XINFERENCE_BASE_URL") + "/v1",
)

client.chat.completions.create(
    model="deepseek-r1-distill-qwen",
    messages=[
        {
            "content": "中国的首都是哪里?",
            "role": "user",
        }
    ],
    max_tokens=1024,
)
```
3. 输出的choices为空，model为返回内容
```
ChatCompletion(id='chatbc021dc4-f3e3-11ef-9997-0242ac170002', choices=None, created=1740534502, model=[{'index': 0, 'message': {'role': 'assistant', 'content': '好的，我现在要回答的问题是“中国的首都是哪里？”嗯，这是一个基本的问题，但作为刚开始学习的人，我得仔细思考一下，确保自己正确无误。\n\n首先，我需要明确什么是首都。首都通常是一个国家的政治和行政中心，是政府所在地。对于中国来说，首都是北京。这一点我记得没错，对吗？让我再确认一下。\n\n我可以回忆一些课本或者可靠的信息来源。比如，中国的领导人通常在北京办公，全国人民代表大会也是在北京召开的，这些都说明北京是全国的政治中心。除此之外，北京也是中国的文化和历史中心，拥有众多的名胜古迹，像故宫、长城、天安门广场等等，这些都是中国的重要象征，进一步巩固北京作为首都的地位。\n\n另外，历史上的一些事件也会支持这一点。比如，北京是元、明、清历代的都城，虽然中间也有迁移的情况，但现代中国的首都一直定在北京。这一点在历史课本中应该有提到。\n\n再者，我可以通过对比其他城市来确认。上海是一个经济中心，广州、深圳是经济发达的城市，但它们都不是首都。因此，当问题问到中国首都是哪里时，答案只能是北京。\n\n当然，也有可能会有例外的情况，比如在战争期间或者其他特殊情况，有时候政府可能会迁移，但目前情况下，北京一直是中国的正式首都。\n\n总结一下，经过这些思考和验证，我对这个问题有了更深入的理解，也更加确定答案的正确性。所以，答案应该就是：中国的首都是北京，位于华北地区，是国家的政治、文化中心，拥有丰富的历史和文化底蕴，以及重要的国际影响力。\n\n除了地理位置和政治因素，北京的经济和科技发展也非常突出，中关村科技园区是全国科技创新的中心，这进一步突出了北京的重要地位。同时，北京也是国际交流的重要城市，举办过多次国际会议和大型活动，如奥运会和APEC会议，这也与其首都的地位相符。\n\n此外，我也记得在现行的行政区划中，北京是一个直辖市，享有省级行政级别的待遇，这与首都的地位是一致的。直辖市通常在政治经济上的重要性更高，这一点也支持北京作为首都的选择。\n\n可能还有其他细节需要注意，比如中国的特别行政区，如香港和澳门，它们不是首都，而是特别行政区，各自有不同的法律体系，这也体现了中国整体的行政区划和首都的地位是分开的。\n\n综上所述，通过多方面的思考和分析，我确认了中国首都是北京，这一点是明确的，没有疑问。\n</think>\n\n中国的首都是北京，位于中国的华北地区，是国家的政治、经济、文化中心，拥有悠久的历史和丰富的文化底蕴，同时也是国际交流的重要城市，体现了一个国家的政治和行政中心地位。'}, 'finish_reason': 'stop'}], object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=554, prompt_tokens=10, total_tokens=564, completion_tokens_details=None, prompt_tokens_details=None))

```

### Expected behavior / 期待表现

返回内容应该在choices里面
