### ISSUE TITLE
使用官方提供的Qwen2.5-vl-Instruct-AWQ模型自定义导入后，传入图片发生OOM

### ISSUE THREAD

**Issue by chenxin03** [xorbitsai/inference#2957]
### System Info / 系統信息

OS: Ubuntu 20.04.1
GPU: 3090ti 24G
python: 3.10.16
torch: 2.5.1+cu124
torchvision: 0.20.1+cu124
transformers: 4.50.0.dev0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Name: xinference
Version: 1.2.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 8888

### Reproduction / 复现过程

1、启动xinference-local，在WEBUI配置自定义AWQ模型
```yaml
{
    "version": 1,
    "context_length": 128000,
    "model_name": "Qwen2.5-VL-7B-Instruct-AWQ",
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "chat",
        "vision"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "qwen2.5-vl-instruct",
    "model_specs": [
        {
            "model_format": "awq",
            "model_size_in_billions": 7,
            "quantizations": [
                "8"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/home/cnbot/zz/qwen/models/Qwen/Qwen2___5-VL-7B-Instruct-AWQ/",
            "model_revision": null
        }
    ],
    "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}",
    "stop_token_ids": [
        151645,
        151643
    ],
    "stop": [
        "<|im_end|>",
        "<|endoftext|>"
    ],
    "is_builtin": false
}
```
2、使用openai传入图片，报错OOM
```python
from openai import OpenAI
from PIL import Image
import base64
import io

with Image.open('./demo.jpeg') as img:
    img_byte_arr = io.BytesIO()
    img.save(img_byte_arr, format='JPEG', quality=20)
    img_byte_arr = img_byte_arr.getvalue()
    img_base64 = "data:image/jpeg;base64," + base64.b64encode(img_byte_arr).decode('utf-8')

client = OpenAI(base_url="http://0.0.0.0:8888/v1", api_key="abc")

response = client.chat.completions.create(
    model='Qwen2.5-VL-3B-Instruct-AWQ',
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text", 
                    "text": '请描述这张图片。',
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": img_base64,
                    },
                },
            ],
        }
    ],
)

print(response.choices[0].message.content)
```
报错：
```
openai.InternalServerError: Error code: 500 - {'detail': '[address=0.0.0.0:15039, pid=4128] Model actor is out of memory, model id: Qwen2.5-VL-3B-Instruct-AWQ, error: CUDA out of memory. Tried to allocate 12.20 GiB. GPU 0 has a total capacity of 23.64 GiB of which 6.47 GiB is free. Including non-PyTorch memory, this process has 16.98 GiB memory in use. Of the allocated memory 16.59 GiB is allocated by PyTorch, and 77.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)'}
```

### Expected behavior / 期待表现

使用Qwen官方的测试demo可以调整图片处理的最大最小值，请问自定义模型可以调整这个参数吗？
```python
min_pixels = 256*28*28
max_pixels = 512*28*28
processor = AutoProcessor.from_pretrained(model_dir, min_pixels=min_pixels, max_pixels=max_pixels)
```
