### ISSUE TITLE
使用docker部署在页面不可见SGlang推理引擎选项

### ISSUE THREAD

**Issue by Sos-Zachary** [xorbitsai/inference#3012]
### System Info / 系統信息

ubuntu20.04, cuda12.4, torch2.5 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.0.post2

### The command used to start Xinference / 用以启动 xinference 的命令

```yaml
xinference:

    image: xprobe/xinference:v1.3.0.post2

    restart: always

    command: xinference-local -H 0.0.0.0

    ports: # 不使用 host network 时可打开.

      - "9997:9997"

    # network_mode: "host"

    # 将本地路径(~/xinference)挂载到容器路径(/root/.xinference)中,

    # 详情见: https://inference.readthedocs.io/zh-cn/latest/getting_started/using_docker_image.html

    volumes:

      - ~/xinference:/root/.xinference

      # - ~/xinference/cache/huggingface:/root/.cache/huggingface

      # - ~/xinference/cache/modelscope:/root/.cache/modelscope

    deploy:

      resources:

        reservations:

          devices:

            - driver: nvidia

              count: all

              capabilities: [gpu]


    # 模型源更改为 ModelScope, 默认为 HuggingFace

    environment:

      - XINFERENCE_MODEL_SRC=modelscope
 ```

>docker compose up -d

拉取后发现无法找到SGlang按钮
因此进入仓库执行

> pip install xinference[sglang]

![Image](https://github.com/user-attachments/assets/e42cb2cd-2e42-47cb-816a-0f507f882052)
重启项目

> docker compose down/up

依旧是没有该选项
![Image](https://github.com/user-attachments/assets/ca12cd1a-7c08-4c39-a759-c758e2ae5dc0)

### Reproduction / 复现过程

直接拉取docker镜像

### Expected behavior / 期待表现

可以选择SGlang引擎
