### ISSUE TITLE
无法使用vllm的工具调用参数enable-auto-tool-choice和tool-call-parser

### ISSUE THREAD

**Issue by elepherai** [xorbitsai/inference#3062]
### System Info / 系統信息

xprobe/xinference:v1.2.1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference==1.2.1
vllm==0.6.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

docker-compose.yaml
```YAML
services:
  xinference:
    image: xprobe/xinference:v1.2.1
    container_name: xinference
    volumes:
      - /etc/localtime:/etc/localtime
      - ./.xinference:/root/.xinference
      - ./auth_config.json:/root/auth_config.json
      - ./scripts:/workspace/scripts
      - /data/ai_deploy/models/pretrained/huggingface:/root/.cache/huggingface
      - /data/ai_deploy/models/pretrained/modelscope:/root/.cache/modelscope
    working_dir: /workspace/scripts
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
      - HF_ENDPOINT=https://hf-mirror.com
    command: xinference-local --host 0.0.0.0 --port 9997 --log-level debug --auth-config /root/auth_config.json
    shm_size: 128gb
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
```

### Reproduction / 复现过程

```shell
xinference launch \
--api-key sk-xxxx\
--model-engine vLLM \
--model-name qwen2.5-instruct \
--model-uid Qwen2.5-7B-Instruct-GPTQ-Int4-temp \
--size-in-billions 7 \
--model-format gptq \
--quantization Int4 \
--max_model_len 10240 \
--endpoint http://0.0.0.0:9997 \
--gpu-idx "1" \
--gpu_memory_utilization 0.95 \
--enable-auto-tool-choice \
--tool-call-parser=hermes
```

报错：AsyncEngineArgs.__init__() got an unexpected keyword argument 'enable-auto-tool-choice'

![Image](https://github.com/user-attachments/assets/33adad15-3236-465a-bc73-16005d11159d)

### Expected behavior / 期待表现

无报错，正常使用vllm的工具调用能力。
