### ISSUE TITLE
docker启动失败,进入容器提示Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by qlanto224** [xorbitsai/inference#3223]
### System Info / 系統信息

os: ubuntu 24.04
docker:24.0.7
docker-compose: 2.27.0
CUDA Version: 12.4
Driver Version: 550.144.03

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

docker镜像版本: v1.4.1

### The command used to start Xinference / 用以启动 xinference 的命令

docker-compose.yml:
```yml
services:
  xinference:
    image: xprobe/xinference:v1.4.1
    container_name: xinference
    ports:
      - 9999:9999
    volumes:
      - ./.xinference:/data/.xinference
      - ./huggingface:/data/.cache/huggingface
      - ./modelscope:/data/.cache/modelscope
    environment:
      - TZ=Asia/Shanghai
      - XINFERENCE_HOME=/data
      - XINFERENCE_MODEL_SRC=modelscope
    restart: unless-stopped
    command: xinference-local --host 0.0.0.0 --port 9999
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```

### Reproduction / 复现过程

docker-compose up -d

### Expected behavior / 期待表现

正常启动
