### ISSUE TITLE
XINFERENCE Data cannot be persisted

### ISSUE THREAD

**Issue by freemankevin** [xorbitsai/inference#3231]
### System Info / 系統信息

ubuntu 22.04.5 lts + docker compose 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

compose file.
```yaml
  xinference:
    image: "${XINFERENCE_IMAGE}"
    container_name: xinference
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
      #- XINFERENCE_HOME=/xinference
      - XINFERENCE_HOME=/root/.xinference
    ports:
      - "${XINFERENCE_PORT:-9997}:9997"
    command: xinference-local -H 0.0.0.0 --log-level info
    restart: always
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/xinference/metadata:/root/.xinference
      - ./data/xinference/models:/root/.xinference/models
      #- ./data/xinference/metadata:/root/.xinference 
      #- ./data/xinference/cache:/root/.cache/modelscope
      #- ./data/xinference/models:/xinference/models
      #- ./data/xinference/logs:/xinference/logs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9997/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - middleware
```

.env file
```shell
# Xinference
XINFERENCE_IMAGE="xprobe/xinference:latest"
XINFERENCE_PORT="29997"
```

### Reproduction / 复现过程

```shell
(base) ubuntu@ta:~/workspace/base/middleware$ ll ./data/xinference/models/
total 8.0K
drwxrwxr-x 3 ubuntu ubuntu 4.0K  4月 11 10:31 bge-large-zh-v1.5
drwxrwxr-x 2 ubuntu ubuntu 4.0K  4月 11 10:31 text2vec-large-chinese
```

### Expected behavior / 期待表现

After the service is restarted, the offline model I registered previously still exists, instead of needing to be manually re-registered.

```shell
curl -X POST http://127.0.0.1:29997/v1/models \
  -H "Content-Type: application/json" \
  -d '{
    "model_name": "bge-large-zh-v1.5",
    "model_type": "embedding",
    "model_path": "/root/.xinference/models/bge-large-zh-v1.5",
    "model_format": "pytorch",
    "persist": true
  }'


curl -X POST http://127.0.0.1:29997/v1/models \
  -H "Content-Type: application/json" \
  -d '{
    "model_name": "text2vec-large-chinese",
    "model_type": "embedding",
    "model_path": "/root/.xinference/models/text2vec-large-chinese",
    "model_format": "pytorch",
    "persist": true
  }'
```
