### ISSUE TITLE
HAMi integration related, is it on the roadmap?

### ISSUE THREAD

**Issue by wawa0210** [xorbitsai/inference#3255]
I am from the HAMi maintainer team. Currently, HAMi(https://github.com/Project-HAMi/HAMi) is a CNCF project and a CNAI Landscape project, focusing on the field of heterogeneous GPU virtualization, further maximizing GPU utilization & unified management, scheduling, and monitoring of heterogeneous GPUs. Currently the community has nearly 100+ endusers.

Core Features

- GPU sharing, multiple tasks can share an GPU (supporting QOS isolation of GPU Core and Memory)
- Unified support for heterogeneous GPUs, currently supports NVIDIA, Ascend, Hygon, Metax, Cambrian, Iluvatar, and Mthreads
- Rich, flexible, and scenario-specific scheduling strategies
- Support specify a device model and schedule tasks to a GPU of a specified model
- Support specify a UUID to schedule tasks to a GPU with a specified UUID
- Node & AI chip-level stacking and scattering scheduling.
  - Binpack
  - Spread
- GPU Affinity Topology-aware scheduling
- Numa affinity scheduling
- GPU memory, Core Oversubscriptions
- Task prioritization mechanism

I understand that xinference should be able to integrate with HAMi, which can further improve the worker pod GPU utilization. I wonder if the xinference community will consider this.We can help

**Comment by qinxuye** [comment]
Thanks, HAMi looks great.

IMHO, HAMi should be working on the k8s layer? If Xinference cluster created based on HAMi, we should be able to leverage abilities of HAMi?

**Comment by wawa0210** [comment]
> Thanks, HAMi looks great.
> 
> IMHO, HAMi should be working on the k8s layer? If Xinference cluster created based on HAMi, we should be able to leverage abilities of HAMi?

Of course, HAMi is a complete technology stack built on Kubernetes.

![Image](https://github.com/user-attachments/assets/90a3a2f3-c949-463b-b7de-6a5d94fc6b1a)

If we need to share the GPU, we only need a simple declaration

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 2 # declare how many physical GPUs the pod needs
          nvidia.com/gpumem: 3000 # identifies 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # identifies 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)
```
