### ISSUE TITLE
xinference oauth启动报错导致登录后自动退出

### ISSUE THREAD

**Issue by yidasanqian** [xorbitsai/inference#3384]
docker compose 
```
version: '3.8'
services:
  xinference-auth:
    container_name: xinference-auth
    image: xprobe/xinference:v1.5.0
    restart: always
    environment:
      - XINFERENCE_HOME=/data
      - XINFERENCE_MODEL_SRC=modelscope
    command: xinference-local -H 0.0.0.0 --auth-config /config/auth-config.json
    ports:
      - "19998:9997"  
    volumes:
      - /HDD/docker-xinference/data:/data
      - /HDD/models:/models
      - /HDD/datasets:/datasets
      - ./auth-config.json:/config/auth-config.json
    shm_size: '32g'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            device_ids: ['0', '1','2','3']

```
auth-config.json
```
{
    "auth_config": {
        "algorithm": "HS256",
        "secret_key": "b9a599f2ab678725cd970555b5d12f25bcdc06f97bbc5000e8c2cb7a358f0773",
        "token_expire_in_minutes": 30
    },
    "user_config": [
        {
            "username": "user1",
            "password": "secret1",
            "permissions": [
                "admin"
            ],
            "api_keys": [
                "sk-nkQwYmWk8Rqt1"
            ]
        },
        {
            "username": "user2",
            "password": "secret2",
            "permissions": [
                "models:list",
                "models:read"
            ],
            "api_keys": [
                "sk-nkQwYmWk8Rqt2"
            ]
        }
    ]
}
```
报错如下

![Image](https://github.com/user-attachments/assets/01fb950e-a475-4f90-ba03-d107604ea18b)
**导致web ui登录后1分钟内自动退出登录**

![Image](https://github.com/user-attachments/assets/e84da859-57b4-4896-b68b-77fdb9070b81)
