### ISSUE TITLE
k8s 部署，每个 worker 可以单独指定 GPU 资源需求

### ISSUE THREAD

**Issue by lordk911** [xorbitsai/inference#3740]
### Feature request / 功能建议

k8s with hami 具备 GPU 虚拟化能力，可以更灵活及充分的利用 GPU资源，因为基于k8s 部署inference 时能够单独指定每个 worker的资源很有必要。比如，大模型就独占 GPU, 小模型可以共享一个 GPU, 目前 worker 的 deployment 模板是固定的，无法实现灵活的资源需求配置

![Image](https://github.com/user-attachments/assets/0cbe9c63-88f7-454e-ab5c-ba81c2e1ad6b)

如图，2 台机器 4 张 GPU, 可以按需分配不同大小的 worker

![Image](https://github.com/user-attachments/assets/48c91fe8-efaa-4a45-84da-6b71e15d50fe)

因此我可以在 2 张 GPU 上部署超过 2 个模型

### Motivation / 动机

如上

### Your contribution / 您的贡献

none

**Comment by qinxuye** [comment]
有啥思路吗？

**Comment by lordk911** [comment]
1、在 values.yaml 新增一个配置：

```
# common used configurations
config:
  xinference_image: ""
  curl_image: curlimages/curl:8.8.0
  image_pull_policy: ""
  worker_num: 1
  # 新增：单独配置每个 worker 的资源（如 GPU），如未配置则使用全局配置
  workers: []
  # 示例：
  # workers:
  #   - name: worker-0
  #     resources:
  #       requests:
  #         cpu: "2"
  #         memory: 8Gi
  #         nvidia.com/gpu: "1"
  #       limits:
  #         cpu: "2"
  #         memory: 8Gi
  #         nvidia.com/gpu: "1"
  #     vgpu:
  #       enabled: true
  #       resources:
  #         requests:
  #           cpu: "2"
  #           memory: 8Gi
  #         limits:
  #           cpu: "2"
  #           memory: 8Gi
  #           nvidia.com/gpu: "1"
  #           nvidia.com/gpumem-percentage: 50
  #           nvidia.com/gpucores: 50
```

2、在 deployment-worker.yaml 中读workers配置，去动态生成 Deployment

```
{{- range $i, $worker := .Values.config.workers }}
---
apiVersion: apps/v1
kind: Deployment
```
